/**
 * Test helpers shared by the webview-* test suites.
 *
 * This file is not a *.test.ts file on purpose: it is only ever imported by
 * the test files themselves and is never reached from the production import
 * graph (webpack only follows imports from `src/extension.ts`), so it will
 * not be bundled into the published extension.
 */
import type { WebviewTranslations } from "./webview-html";

/**
 * Returns a fully-populated `WebviewTranslations` object suitable for driving
 * the webview IIFE generators in unit tests. Pass a partial object to override
 * only the fields you care about.
 */
export function makeTr(overrides?: Partial<WebviewTranslations>): WebviewTranslations {
  return {
    locale: "en",
    history: "History",
    threads: "Threads",
    sessions: "Sessions",
    tasks: "Tasks",
    work: "Work",
    newThread: "New Thread",
    compact: "Compact",
    interrupt: "Interrupt",
    toggleHistory: "Toggle History",
    send: "Send",
    inputPlaceholder: "Type a message...",
    initializing: "Initializing...",
    ready: "Ready",
    thinking: "Thinking...",
    streaming: "Streaming...",
    processing: "Processing...",
    error: "Error",
    approvalAwaiting: "Approval Required",
    noConversations: "No conversations",
    noTasks: "No tasks",
    threadsCountPattern: "{n} threads",
    modelLabel: "Model",
    workspaceLabel: "Workspace",
    loadedThreadPattern: "Loaded: {0}",
    showAllWorkspaces: "Show all workspaces",
    filterCurrentWorkspace: "Current workspace",
    approvalRequired: "Approval required",
    allow: "Allow",
    deny: "Deny",
    thinkingToggle: "Thinking",
    thinkingOpen: "▶ Thinking",
    thinkingClose: "▼ Thinking",
    modeLabel: "Mode",
    reasoningEffortLabel: "Reasoning",
    welcomeTitle: "CodeWhale",
    welcomeSubtitle: "Your AI coding partner",
    welcomeQuote: "The best way to predict the future is to invent it.",
    welcomeQuoteAuthor: "Alan Kay",
    welcomeSuggestionTitle: "Try asking",
    welcomeSuggestion1: "Explain this code",
    welcomeSuggestion2: "Write a test",
    welcomeSuggestion3: "Find bugs",
    welcomeSuggestion4: "Refactor this",
    noActiveWork: "No active work",
    cancel: "Cancel",
    goal: "Goal",
    checklist: "Checklist",
    strategy: "Strategy",
    cycles: "Cycles",
    coherenceHealthy: "Healthy",
    coherenceGettingCrowded: "Getting crowded",
    coherenceRefreshingContext: "Refreshing context",
    coherenceVerifyingRecentWork: "Verifying recent work",
    coherenceResettingPlan: "Resetting plan",
    completionPct: "0%",
    readyTimedOut: "Ready timed out",
    note: "Note",
    noPreviousMessage: "No previous message",
    justNow: "just now",
    minutesAgoPattern: "{n} min ago",
    hoursAgoPattern: "{n}h ago",
    daysAgoPattern: "{n}d ago",
    commandMode: "/mode",
    commandModel: "/model",
    commandModels: "/models",
    commandReasoning: "/reasoning",
    commandConfig: "/config",
    commandSettings: "/settings",
    commandClear: "/clear",
    commandInterrupt: "/interrupt",
    commandHelp: "/help",
    commandCompact: "/compact",
    commandExit: "/exit",
    commandRename: "/rename",
    commandSave: "/save",
    commandExport: "/export",
    commandContext: "/context",
    commandTokens: "/tokens",
    commandCost: "/cost",
    commandStatus: "/status",
    commandHome: "/home",
    commandWorkspace: "/workspace",
    commandTask: "/task",
    commandJobs: "/jobs",
    commandNote: "/note",
    commandMemory: "/memory",
    commandTrust: "/trust",
    commandVerbose: "/verbose",
    commandTheme: "/theme",
    commandUndo: "/undo",
    commandRetry: "/retry",
    commandShare: "/share",
    commandGoal: "/goal",
    commandSkills: "/skills",
    commandSkill: "/skill",
    commandMcp: "/mcp",
    commandNetwork: "/network",
    commandProvider: "/provider",
    commandQueue: "/queue",
    commandStash: "/stash",
    commandHooks: "/hooks",
    commandSubagents: "/subagents",
    commandAgent: "/agent",
    commandLinks: "/links",
    commandFeedback: "/feedback",
    commandAttach: "/attach",
    commandAnchor: "/anchor",
    commandSessions: "/sessions",
    commandLoad: "/load",
    commandCycles: "/cycles",
    commandCycle: "/cycle",
    commandRecall: "/recall",
    commandRelay: "/relay",
    commandInit: "/init",
    commandLsp: "/lsp",
    commandReview: "/review",
    commandRestore: "/restore",
    commandRlm: "/rlm",
    commandChange: "/change",
    commandCache: "/cache",
    commandProfile: "/profile",
    commandTranslate: "/translate",
    commandSystem: "/system",
    commandEdit: "/edit",
    commandDiff: "/diff",
    commandStatusline: "/statusline",
    commandLogout: "/logout",
    commandNotAvailableInGui: "Not available in GUI",
    attachFiles: "Attach files",
    removeAttachment: "Remove",
    attachedFileCount: "{n} files attached",
    fileNotSupported: "File type not supported",
    changes: "Changes",
    noFileChanges: "No file changes in this session",
    undoUnsupportedTooltip: "Undo not supported",
    retryUnsupportedTooltip: "Retry not supported",
    revertUnsupportedTooltip: "Revert not supported",
    fileCreated: "Created",
    fileDeleted: "Deleted",
    fileModified: "Modified",
    viewDiff: "View Diff",
    viewDiffTooltip: "View file diff",
    openFile: "Open File",
    openFileTooltip: "Open file in editor",
    revertFile: "Revert",
    revertFileTooltip: "Revert file changes",
    fileChanges: "File Changes",
    userInputAwaiting: "Input required",
    searchSessions: "Search",
    searchPlaceholder: "Search sessions...",
    deleteSession: "Delete",
    deleteSessionConfirmTitle: "Delete session?",
    deleteSessionConfirmMessage: 'This will permanently delete the session "{title}". This cannot be undone.',
    deleteSessionConfirmButton: "Delete",
    deleteSessionSuccess: "Session deleted",
    deleteSessionFailed: "Failed to delete session",
    noSearchResults: "No matching sessions",
    ...overrides,
  };
}
